### ISSUE TITLE
maxArea causes hard crash of Google Chrome on Samsung Galaxy S20+

### ISSUE THREAD

**Issue by ercgrat** [jhildenbiddle/canvas-size#11]
This was end-user reported. I was able to reproduce on browserstack with the sandbox below. This works in other Chrome browsers, so could be a Chrome bug. I reported it to Chrome as well.

https://codesandbox.io/s/hopeful-dan-0mmr2?file=/src/App.js

![image](https://user-images.githubusercontent.com/5784425/109372168-22c8ef80-7876-11eb-89a1-33f34b76d042.png)

**Comment by jhildenbiddle** [comment]
Interesting.

Unfortunately, this is the kind of error you will see in some browsers when you try to render a `canvas` element that exceeds the bounds or memory limitations of the browser/device. Older browsers were particularly bad with these hard crashes, but most modern browsers are able to handle these scenarios more gracefully by failing silently without taking down the entire tab/process/browser.

Is this happening on a real device or simulator / VM? The reason I ask is because virtual environments can produce inconsistent results due to the "virtualized" hardware they use. This is covered in the [Known Issues](https://github.com/jhildenbiddle/canvas-size/tree/dev#known-issues) section of the docs:

> 2. Virtual environments may produce inconsistent results
>
> Tests conducted on virtual machines may produce results that differ from actual hardware. This is to be expected, as the virtualized hardware used in these environments can impose its own unique size limitations separate from the browser.
> 
> In some virtualized environments (mostly with older browsers), canvas-size may produce inconsistent results or fail all tests when calling maxArea(), maxHeight(), maxWidth(), and test() using options.sizes. This is a result of the virtual GPU failing after a test canvas exceeds the browser's size limitations, causing all subsequent tests to fail even for canvas dimensions that are actually supported by the browser. The easiest and most reliable way to address these issues is to use a GPU-optimized virtual machine. If this isn't possible and your VM only supports software rendering, avoid iterating over canvas dimensions that exceed the browser's size limitations and instead specify dimensions that are known to be supported by the browser.

**Comment by ercgrat** [comment]
It happens on the actual device, as I mentioned, end-user reported! I’ll comment here if I get any information from my chrome report.

**Comment by jhildenbiddle** [comment]
Got it. Based on the screenshot it looked like an emulator.

**Comment by ercgrat** [comment]
You’re correct I just had to reproduce it in an emulator :)

**Comment by jhildenbiddle** [comment]
@ercgrat --

It doesn't appear there is anything to do on my end here, so I'm going to close this issue for now. Happy to reopen and discuss further if/when we have more information to work with.
