### ISSUE TITLE
Crashing on Android Browsers

### ISSUE THREAD

**Issue by followbl** [jhildenbiddle/canvas-size#13]
1. Thank you for this library - it's 100% needed.
2. My apologies in advance if this log is annoying - just figured you'd wanna know. Read through as much as I possibly could in the readme, plus related issues...

This is consistently crashing the Chrome Browser for me on Android Browserstack Pixel 4/5. This was first reported by users in production, so I know it's not just a VM limitation that was outlined in your very helpful readme. 

For reference - using it as recommended in the readme as well..

```js
const canvasLimitation = await canvasSize.maxArea({
      usePromise: true,
      useWorker: false,
    });
```

to reproduce if you'd like you can actually just fire up one of those devices in browserstack and go to your test url.

https://jsbin.com/megedep/1/edit?js,output

I've had it log the failure in the console and crash the browser.

Happy to help debug if you'd like.

**Comment by jhildenbiddle** [comment]
Thanks for filing the issue, @followbl. Happy to take a look at this. Let me see what I come up with over the weekend and I'll report back.

**Comment by jhildenbiddle** [comment]
Apologies for the delayed response, @followbl.

In my limited testing with the Pixel 5 VM on BrowserStack I experienced inconsistent results: both the JSBin and CodeSandbox demos failed and completed successfully when reloaded several times. Here are the results of my testing:

🎉 **Test 1: PASS (Pixel 5 VM + JSBin demo)**

<img width="466" alt="pixel5-1" src="https://user-images.githubusercontent.com/442527/116139042-312b6000-a69b-11eb-96d7-70831703a13f.png">

⚠️ **Test 2: FAIL (Pixel 5 VM + Codesandbox demo)**

<img width="459" alt="pixel5-2" src="https://user-images.githubusercontent.com/442527/116139383-941cf700-a69b-11eb-8c8b-9ba4d3d235da.png">

🎉 **Test 3: PASS (Pixel 5 VM + Codesandbox demo)**

<img width="459" alt="pixel5-3" src="https://user-images.githubusercontent.com/442527/116139538-bca4f100-a69b-11eb-8f1c-aa991c00d881.png">

Given these inconsistent results, my assumption would have been that the Browserstack VM is not as reliable as testing on real hardware. Since your users are experiencing issue on real hardware I can only assume that platform itself is unstable when rendering large canvas elements. This isn't totally unexpected given the hardware limitations on mobile devices and the RAM requirements of rendering large in-memory canvas elements.

Fortunately, there is an easy fix: limit the maximum canvas size used for testing. Since this issue is only affecting mobile devices, use the [mobile test results](https://github.com/jhildenbiddle/canvas-size#mobile) available in the [README.md](https://github.com/jhildenbiddle/canvas-size/blob/master/README.md) to find a suitable max value.

```js
const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);

const canvasLimitation = await canvasSize.maxArea({
  max: isMobile ? 8192 : null,
  usePromise: true,
  useWorker: false,
});
```

Using this approach I was able to reload a modified JSBin demo multiple times without issue.

* https://jsbin.com/zufiralaja/1/edit?js,output

Hope this helps!

**Comment by followbl** [comment]
@jhildenbiddle extremely detailed response - makes total sense what you laid out. Will test out your solution and report back for 💩 's and giggles

**Comment by rnike** [comment]
I use the mobile test results from README.md but it still crashes

```
  canvasSize.maxArea({
    usePromise: true,
    max: 16384,
  });
```

My device info
- Android 13
- Chrome 119.0.6045.163

**Comment by rnike** [comment]
@jhildenbiddle Still crashing on the Android device, currently I'm using it with `max:8192` to avoid the crash.

**Comment by jhildenbiddle** [comment]
@rnike --

Everything looks okay when I test the [full page CodePen demo](https://codepen.io/jhildenbiddle/full/dyrQGNx) on a Pixel 4 and Pixel 8 Pro using real devices via [BrowserStack](https://www.browserstack.com):

#### Google Pixel 4

![Google Pixel 4](https://github.com/jhildenbiddle/canvas-size/assets/442527/6a6aa42d-20bb-4e26-ae3f-9188fd53d7fa)

#### Google Pixel 8 Pro

![Google Pixel 8 Pro](https://github.com/jhildenbiddle/canvas-size/assets/442527/25f66cdf-ceee-4055-8a30-6d55e9cc7c5f)

**Comment by webceoboy** [comment]
+1
