### ISSUE TITLE
Test process questions

### ISSUE THREAD

**Issue by Jamie5** [jhildenbiddle/canvas-size#15]
Hi, I have a few questions about how the testing process works

1. It is noted that "Some browsers become unresponsive during tests" during the process. Is there a general sense of which browsers suffer about how much delay?
2. In the test, we copy a pixel from one canvas to another, then read the second canvas. I guess just reading a pixel from the first pixel would not be accurate enough of a test for some reason?

**Comment by jhildenbiddle** [comment]
Hi @Jamie5.

Apologies for the slow response.

> 1. It is noted that "Some browsers become unresponsive during tests" during the process. Is there a general sense of which browsers suffer about how much delay?

The short answer is no, simply because there are so many factors to consider:

* Which browser version is being used?
* Are tests executed on the main thread or in a web worker?
* Are `<canvas>` calculations handled by the CPU or the GPU?
* How fast is the CPU?
* How much RAM is available?
* How many tests are being executed?
* How large are the canvas elements being tested?

There are logical assumptions you can make from the above items that are generally accurate:

* Browsers that support [OffscreenCanvas()](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas/OffscreenCanvas#browser_compatibility) are best for handling long-running tests (usually)
* Modern browsers are faster than legacy browsers
* Modern hardware is faster than legacy hardware
* GPU rendering is faster than CPU rendering (usually)
* Running fewer tests is faster than running a lot of tests
* Testing smaller canvas dimensions is faster than testing larger canvas dimensions

> 2. In the test, we copy a pixel from one canvas to another, then read the second canvas. I guess just reading a pixel from the first pixel would not be accurate enough of a test for some reason?

This is an optimization done to test time. Specifically, it reduces the time it takes for `getImageData()` to complete.

Writing data to a `<canvas>` element is fast but reading data (particularly from a large canvas) is slow. To work around this, a test canvas is created with a test pixel rendered in the bottom-right corner, then the test canvas is drawn on top of a separate 1x1 canvas so that the test pixel is visible. This significantly reduces the amount of time needed to verify that the test pixel was drawn properly on the test canvas, which is how this library determines if a canvas test is successful.

Hope this helps. Happy to answer more questions if you have them. Closing the issue as resolved for now.

Thanks!
